import {
  ValidateFlat,
  ValidateDoorPhone,
  ValidatePorch,
  ValidateFloor,
  ValidateCourierComment,
} from '@modules/validation';

export default {
  addressInputs: {
    apartment_or_office: {
      id: 'form__line__flat__input',
      placeholder: 'Кв./Офис',
      type: 'text',
      required: true,
      maxLength: 20,
      movePlaceholderOnInput: true,
      validator: ValidateFlat,
      hideErrors: true,
    },
    intercom: {
      id: 'form__line__door_phone__input',
      placeholder: 'Домофон',
      type: 'text',
      required: true,
      maxLength: 20,
      movePlaceholderOnInput: true,
      validator: ValidateDoorPhone,
      hideErrors: true,
    },
    entrance: {
      id: 'form__line__porch__input',
      placeholder: 'Подъезд',
      type: 'text',
      required: true,
      maxLength: 20,
      movePlaceholderOnInput: true,
      validator: ValidatePorch,
      hideErrors: true,
    },
    floor: {
      id: 'form__line__floor__input',
      placeholder: 'Этаж',
      type: 'number',
      required: true,
      min: 1,
      max: 100,
      movePlaceholderOnInput: true,
      validator: ValidateFloor,
      hideErrors: true,
    },
  },
  courier_comment: {
    id: 'order_page_comment_input',
    placeholder: 'Комментарий курьеру',
    required: false,
    type: 'text',
    validator: ValidateCourierComment,
    maxLength: 300,
    hideErrors: true,
  },
};
