name: Deploy Frontend

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4.2.2

      - name: Установка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Установка зависимостей
        run: npm install

      - name: Создание env файла
        run: |
          touch .env
          echo GEOSUGGEST_API_KEY=${{ secrets.GEOSUGGEST_API_KEY }} >> .env
          echo GEOCODER_API_KEY=${{ secrets.GEOCODER_API_KEY }} >> .env
          cat .env

      - name: Очистка локального dist
        run: rm -rf dist

      - name: Сборка проекта
        run: npm run build

      - name: Очистка папки на сервере
        uses: appleboy/ssh-action@master
        with:
          timeout: 10m
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: sudo rm -rf /home/ubuntu/deploy_user/tp_code/frontend/*

      - name: Деплой на сервер
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/*"
          target: "/home/ubuntu/deploy_user/tp_code/frontend"
          strip_components: 1
          overwrite: true
