name: Deploy Frontend

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4.2.2

      - name: Установка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Установка зависимостей
        run: npm install

      - name: Сборка проекта
        run: npm run build

      - name: Деплой на сервер
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "public/*"
          target: "/opt/public"
          strip_components: 1
          overwrite: true